import os
import json
from Bio.PDB import PDBParser
from io import StringIO

# Base path should be the path to where you are keeping most of the mutants, I.E. /research/jagodzinski/interface_mutations/full_protein/DATA/targeted_mutants
# sub_folder should be the specific subdirectory you want to look at. It should start with the PDB id and then one or more sub folders
# For example to find single indels that were done at location 100 in 1brs you would do 1brs/100
# The above example is for single indels and the base_path may change if you're looking for double indels
# Ideally though, only the sub_folder variable should be changing frequently
# Lastly there's the outpath variable which should just be an absolute path to where you want to store the PDBs. A folder should be given here, not a file name.
# Filenames for output will be autogenerated based on the name of the source json file, and they will be deposited in the outpath folder
#


def load_structures(base_path, sub_folder):
    """
    load json structures directly into a list of biopython PDB objects
    base_path: the path where you are keeping most of your mutants
    subfolder: the specific subdirectory you want to look at. It should start with the PDB id and then
               one or more subfolders
    """
    fp = base_path + sub_folder

    files = os.listdir(fp)
    parser = PDBParser(QUIET=True)

    structures = []

    for name in files:
        with open(fp + "/" + name, "r") as input_file:
            pdb_string = json.load(input_file)["pdb_data"]["pdb"] + "END\n"
            structure = parser.get_structure(name.strip(".json"), StringIO(pdb_string))
            structures.append(structure)

    return structures


def main():
    base_path = (
        "/research/jagodzinski/interface_mutations/complete_runs/DATA/targeted_mutants/"
    )
    sub_folder = "1brs/1/"
    load_structures(base_path, sub_folder)


if __name__ == "__main__":
    main()
